/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import tabelas.*;
import cadwebhotel.*;
import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JPanel;
import modelos.*;
import utils.fotoLoad;
import java.awt.*;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.JFrame;

/**
 *
 * @author 00
 */
public class TelaGerenciador extends javax.swing.JFrame {
    hoteisModeloDeTabela eModelHoteis;
    quartoModeloDeTabela eModelQuartos;
    catModeloDeTabela eModelCategoria;
    String fotoHotel="";
    String fotoQuarto="";
    BDConexao myc = new BDConexao();
    int HotelIdselected = 0;
    int QuartoIdselected = 0;
    /**
     * Creates new form TelaGerenciador
     */
    public TelaGerenciador() {
        super("Tela de Gerenciamento do banco de dados");
        initComponents();
        jPanel1.setVisible(true);
        populaTabelaHotel();
        populaTabelaQuartos();
        populaTabelaCat();
        AdicionarCListener();
        this.setLocationRelativeTo(null);
    }
    /**
     * OBJETIVO : Adicionando ChangeListener no JTabbedPane para 
     * identificar quando se muda de guia.
     */
    public void AdicionarCListener()
    {
        ChangeListener changeListener = new ChangeListener() {
        public void stateChanged(ChangeEvent changeEvent) {
            int index = jTabbedPane1.getSelectedIndex();
            switch(jTabbedPane1.getTitleAt(index)+"")
                {
                    case "Hóteis" : populaTabelaHotel();break;
                    case "Quartos": populaTabelaQuartos();break;
                    case "Categorias": populaTabelaCat();break;
                    default : populaTabelaHotel();break;
                }
            }
        };
        jTabbedPane1.addChangeListener(changeListener);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jFrame1 = new javax.swing.JFrame();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtHotelNome = new javax.swing.JTextField();
        txtRating = new javax.swing.JTextField();
        txtCategoriaH = new javax.swing.JTextField();
        txtRua = new javax.swing.JTextField();
        txtCidade = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        btnInserirHotel = new javax.swing.JButton();
        btnAlterarHotel = new javax.swing.JButton();
        btnApagarHotel = new javax.swing.JButton();
        btnVisualizarFotoHotel = new javax.swing.JButton();
        btnHotelEscolherFoto = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        txtNomeBuscaH = new javax.swing.JTextField();
        jButton14 = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        txtCategoriaBuscaHotel = new javax.swing.JTextField();
        txtCidadeBuscaHotel = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtRatingBusca1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TabelaHoteis = new javax.swing.JTable();
        txtRatingBusca2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnInserirQuartos = new javax.swing.JButton();
        btnAlterarQuartos = new javax.swing.JButton();
        btnApagarQuartos = new javax.swing.JButton();
        btnQuartoEscolherFoto = new javax.swing.JButton();
        btnVisualizarFotoQuarto = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        txtQuartosHotelBusca = new javax.swing.JTextField();
        btnPesquisarQuartos = new javax.swing.JButton();
        txtBuscaCategoriaQuarto = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        txtPrecoMaxQuartos = new javax.swing.JTextField();
        txtPrecoMinQuartos = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtHotelIdQuartos = new javax.swing.JTextField();
        txtNumeroQuartos = new javax.swing.JTextField();
        txtClienteIdQuartos = new javax.swing.JTextField();
        txtPrecoQuartos = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaQuartos = new javax.swing.JTable();
        jLabel21 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        txtCategoria = new javax.swing.JTextField();
        txtDescricao = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        btnInserirCat = new javax.swing.JButton();
        btnAlterarCat = new javax.swing.JButton();
        btnExcluirCat = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JSeparator();
        txtDescricaoBuscar = new javax.swing.JTextField();
        btnPesquisarCat = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        TabelaCat = new javax.swing.JTable();
        txtCategoriaBuscar = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        jMenuItem1.setText("jMenuItem1");

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setForeground(new java.awt.Color(51, 51, 51));
        jTabbedPane1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel14.setText("Categoria");

        jLabel15.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel15.setText("Rating");

        jLabel16.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel16.setText("Nome do Hotel");

        jLabel17.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel17.setText("Cidade");

        jLabel18.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel18.setText("Rua");

        txtHotelNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtRating.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtCategoriaH.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtRua.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtCidade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnInserirHotel.setText("INSERIR");
        btnInserirHotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirHotelActionPerformed(evt);
            }
        });

        btnAlterarHotel.setText("ALTERAR");
        btnAlterarHotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarHotelActionPerformed(evt);
            }
        });

        btnApagarHotel.setText("APAGAR");
        btnApagarHotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApagarHotelActionPerformed(evt);
            }
        });

        btnVisualizarFotoHotel.setText("Visualizar Foto");
        btnVisualizarFotoHotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisualizarFotoHotelActionPerformed(evt);
            }
        });

        btnHotelEscolherFoto.setText("Escolher Foto");
        btnHotelEscolherFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHotelEscolherFotoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnApagarHotel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInserirHotel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAlterarHotel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVisualizarFotoHotel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHotelEscolherFoto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInserirHotel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHotelEscolherFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAlterarHotel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnApagarHotel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVisualizarFotoHotel, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jButton14.setText("BUSCAR");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel4.setText("Categoria");

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel5.setText("Cidade");

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel6.setText("Rating");

        TabelaHoteis.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        TabelaHoteis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TabelaHoteisMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(TabelaHoteis);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Até");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel14))
                                .addGap(35, 35, 35)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtRua, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtRating, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtHotelNome, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCategoriaH, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(43, 43, 43)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jSeparator5)
                    .addComponent(jSeparator4)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(txtNomeBuscaH, javax.swing.GroupLayout.DEFAULT_SIZE, 721, Short.MAX_VALUE)
                        .addGap(68, 68, 68)
                        .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(txtCategoriaBuscaHotel, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(txtCidadeBuscaHotel, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(txtRatingBusca1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addGap(25, 25, 25)
                        .addComponent(txtRatingBusca2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 978, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtHotelNome)
                            .addComponent(jLabel16))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCategoriaH, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtRating, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtRua, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomeBuscaH, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                    .addComponent(txtCategoriaBuscaHotel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                    .addComponent(txtCidadeBuscaHotel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtRatingBusca2, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtRatingBusca1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Hóteis", jPanel4);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel3.setText("HotelName");

        btnInserirQuartos.setText("INSERIR");
        btnInserirQuartos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirQuartosActionPerformed(evt);
            }
        });

        btnAlterarQuartos.setText("ALTERAR");
        btnAlterarQuartos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarQuartosActionPerformed(evt);
            }
        });

        btnApagarQuartos.setText("APAGAR");
        btnApagarQuartos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApagarQuartosActionPerformed(evt);
            }
        });

        btnQuartoEscolherFoto.setText("Escolher Foto");
        btnQuartoEscolherFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuartoEscolherFotoActionPerformed(evt);
            }
        });

        btnVisualizarFotoQuarto.setText("Visualizar Foto");
        btnVisualizarFotoQuarto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisualizarFotoQuartoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnApagarQuartos, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInserirQuartos, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAlterarQuartos, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVisualizarFotoQuarto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnQuartoEscolherFoto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addComponent(btnInserirQuartos, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAlterarQuartos, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnApagarQuartos, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnQuartoEscolherFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96)
                .addComponent(btnVisualizarFotoQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btnPesquisarQuartos.setText("BUSCAR");
        btnPesquisarQuartos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarQuartosActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel7.setText("Preço Min");

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel8.setText("Preço Máx");

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 0, 30)); // NOI18N
        jLabel9.setText("Hotel Id");

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 0, 30)); // NOI18N
        jLabel10.setText("Numero do Quarto");

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 0, 30)); // NOI18N
        jLabel11.setText("Cliente_Id");

        jLabel12.setFont(new java.awt.Font("Trebuchet MS", 0, 30)); // NOI18N
        jLabel12.setText("Preço");

        txtHotelIdQuartos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtNumeroQuartos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtClienteIdQuartos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtPrecoQuartos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        TabelaQuartos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TabelaQuartos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TabelaQuartosMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(TabelaQuartos);

        jLabel21.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel21.setText("Categoria");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel3)
                        .addGap(119, 119, 119)
                        .addComponent(txtQuartosHotelBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPesquisarQuartos, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(132, 132, 132)
                                .addComponent(txtBuscaCategoriaQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtPrecoMaxQuartos, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(txtPrecoMinQuartos, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 965, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel11)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel9)
                                                    .addComponent(jLabel12)
                                                    .addComponent(jLabel10))
                                                .addGap(35, 35, 35)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(txtHotelIdQuartos)
                                                    .addComponent(txtNumeroQuartos)
                                                    .addComponent(txtClienteIdQuartos)
                                                    .addComponent(txtPrecoQuartos, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 963, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(19, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(30, 30, 30)
                    .addComponent(jLabel21)
                    .addContainerGap(860, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtHotelIdQuartos)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNumeroQuartos, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtClienteIdQuartos, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtPrecoQuartos, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtQuartosHotelBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnPesquisarQuartos, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtBuscaCategoriaQuarto, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtPrecoMaxQuartos, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtPrecoMinQuartos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(354, 354, 354)
                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                    .addGap(266, 266, 266)))
        );

        jTabbedPane1.addTab("Quartos", jPanel1);

        jLabel19.setFont(new java.awt.Font("Trebuchet MS", 0, 30)); // NOI18N
        jLabel19.setText("Categoria");

        txtCategoria.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtDescricao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel20.setFont(new java.awt.Font("Trebuchet MS", 0, 30)); // NOI18N
        jLabel20.setText("Descrição");

        btnInserirCat.setText("INSERIR");
        btnInserirCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirCatActionPerformed(evt);
            }
        });

        btnAlterarCat.setText("ALTERAR");
        btnAlterarCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarCatActionPerformed(evt);
            }
        });

        btnExcluirCat.setText("APAGAR");
        btnExcluirCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirCatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnExcluirCat, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInserirCat, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAlterarCat, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addComponent(btnInserirCat, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAlterarCat, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnExcluirCat, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btnPesquisarCat.setText("BUSCAR");
        btnPesquisarCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarCatActionPerformed(evt);
            }
        });

        TabelaCat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TabelaCat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TabelaCatMousePressed(evt);
            }
        });
        jScrollPane3.setViewportView(TabelaCat);

        jLabel22.setFont(new java.awt.Font("Trebuchet MS", 0, 30)); // NOI18N
        jLabel22.setText("Descrição");

        jLabel23.setFont(new java.awt.Font("Trebuchet MS", 0, 30)); // NOI18N
        jLabel23.setText("Categoria");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20))
                .addGap(35, 35, 35)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCategoria)
                    .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 978, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtDescricaoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtCategoriaBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(29, 29, 29)
                        .addComponent(btnPesquisarCat, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCategoria)
                            .addComponent(jLabel19))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(103, 103, 103))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel23)
                            .addComponent(txtCategoriaBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtDescricaoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPesquisarCat, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)))
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Categorias", jPanel3);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel13.setText("PAINEL ADMINISTRATIVO DO BANCO DE DADOS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1003, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 842, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 714, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /***
     *  PARTE DE HOTEIS
     */
    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        try {
            int sizeCatBusca = txtCategoriaBuscaHotel.getText().length();
            int sizeCidadeBusca = txtCidadeBuscaHotel.getText().length();
            int sizeRate1 = txtRatingBusca1.getText().length();
            int sizeRate2 = txtRatingBusca2.getText().length();
            int sizeNome = txtNomeBuscaH.getText().length();
            
            // TODO add your handling code here:
            ResultSet Resultado;
            Connection c = myc.criaConexao();
            
            if(sizeCatBusca >0){
                Resultado = CRUDTodos.PesquisarHoteisCategoria(txtCategoriaBuscaHotel.getText(), c);
            }
            else if (sizeCidadeBusca > 0){
                Resultado = CRUDTodos.PesquisarHoteisCidade(txtCidadeBuscaHotel.getText(), c);
            }
            else if(sizeRate1>0 && sizeRate2>0)
            {
                Resultado = CRUDTodos.PesquisarHoteisNota(Integer.parseInt(txtRatingBusca1.getText()), Integer.parseInt(txtRatingBusca2.getText()), c);
            }
            else if(sizeNome>0)
            {
                Resultado = CRUDTodos.PesquisarHoteisNome(txtNomeBuscaH.getText(),c);
            }
            else{
                Resultado = CRUDTodos.PesquisarHoteis(c);
            }
            populaTabelaHotel(Resultado);
            c.close();
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(TelaGerenciador.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton14ActionPerformed

    private void TabelaHoteisMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaHoteisMousePressed
      // TODO add your handling code here:
      if (TabelaHoteis.getSelectedRow() != -1 && TabelaHoteis.getSelectedColumn() != -1 ){
        String id = TabelaHoteis.getModel().getValueAt(TabelaHoteis.getSelectedRow(),0) + "";
        try {
        Connection c = myc.criaConexao();
            populaSelecionado(CRUDTodos.PesquisarHoteisId(Integer.parseInt(id),c));
        c.close();
        }
        catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(TelaGerenciador.class.getName()).log(Level.SEVERE, null, ex);
      }
    }
    }//GEN-LAST:event_TabelaHoteisMousePressed

    private void btnAlterarHotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarHotelActionPerformed
        // TODO add your handling code here:
        FormularioAlteracaoHotel teste = new FormularioAlteracaoHotel(HotelIdselected);
        populaTabelaHotel();
        
    }//GEN-LAST:event_btnAlterarHotelActionPerformed

    private void btnApagarHotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApagarHotelActionPerformed
        // TODO add your handling code here:
        if (HotelIdselected >0)
            try{
                Connection c = myc.criaConexao();
                CRUDTodos.DeletarHoteis(HotelIdselected, c);
                populaTabelaHotel();
            } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(TelaGerenciador.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnApagarHotelActionPerformed

    private void btnInserirHotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirHotelActionPerformed
        // TODO add your handling code here:
        Hoteis e = new Hoteis(txtCategoriaH.getText(), txtHotelNome.getText(), Integer.parseInt(txtRating.getText()), txtRua.getText(), txtCidade.getText(),fotoHotel);
        if (e.isUsed())
        {
            try{
                Connection c = myc.criaConexao();
                CRUDTodos.InserirHoteis(e, c);
                populaTabelaHotel();
            } 
            catch (SQLException | ClassNotFoundException ex) {
                Logger.getLogger(TelaGerenciador.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnInserirHotelActionPerformed

    private void populaTabelaHotel(){
        TabelaHoteis.removeAll();
        List<Hoteis> hoteis = new ArrayList<Hoteis>();
        Hoteis e = null;
        
        // Pega os dados do Banco de Dados
        try{
             Connection c = myc.criaConexao();
             ResultSet dados =  CRUDTodos.PesquisarHoteis(c);
             while (dados.next()){
                 e = new Hoteis(dados.getInt("HotelId"),
                                dados.getString("Category"),
                                dados.getString("HotelName"),
                                dados.getDouble("Rating"),
                                dados.getString("Street"),
                                dados.getString("City"));
                 hoteis.add(e);
             }
             
             c.close();
             
         } catch (ClassNotFoundException | SQLException er)       {
         }
    
       // Cria o modelo e associa com o List
       eModelHoteis = new hoteisModeloDeTabela(hoteis);
       
       // Associa o modelo à tabela
       TabelaHoteis.setModel(eModelHoteis);
    
    }
    
    private void populaSelecionado(ResultSet dados) throws SQLException
    {
        dados.next();
        HotelIdselected = dados.getInt("HotelId");
        txtHotelNome.setText(dados.getString("HotelName"));
        txtCategoriaH.setText(dados.getString("Category"));
        txtRating.setText(dados.getString("Rating"));
        txtRua.setText(dados.getString("Street"));
        txtCidade.setText(dados.getString("City"));
        fotoHotel = dados.getString("fotoH");
    }
    
    private void populaTabelaHotel(ResultSet dados){
        TabelaHoteis.removeAll();
        List<Hoteis> hoteis = new ArrayList<Hoteis>();
        Hoteis e = null;
        
        // Pega os dados do Banco de Dados
        try{
             Connection c = myc.criaConexao();
             while (dados.next()){
                 e = new Hoteis(dados.getInt("HotelId"),
                                dados.getString("Category"),
                                dados.getString("HotelName"),
                                dados.getDouble("Rating"),
                                dados.getString("Street"),
                                dados.getString("City"));
                 hoteis.add(e);
             }
             
             c.close();
             
         } catch (ClassNotFoundException | SQLException er)       {
         }
    
       // Cria o modelo e associa com o List
       eModelHoteis = new hoteisModeloDeTabela(hoteis);
       
       // Associa o modelo à tabela
       TabelaHoteis.setModel(eModelHoteis);
    
    }
    /* FIM DOS HOTEIS*/
    
    
     /**
      * PARTE DOS QUARTOS
      */
     
     
    private void btnPesquisarQuartosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarQuartosActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            ResultSet Resultado;
            Connection c = myc.criaConexao();
            if(txtBuscaCategoriaQuarto.getText().length() >0){
                Resultado = CRUDTodos.PesquisarQuartosCategoria(txtBuscaCategoriaQuarto.getText(), c);
            }
            else if (txtQuartosHotelBusca.getText().length() > 0){
                Resultado = CRUDTodos.PesquisarQuartosHotelNome(txtQuartosHotelBusca.getText(), c);
            }
            else if(txtPrecoMinQuartos.getText().length()>0 && txtPrecoMaxQuartos.getText().length()>0)
            {
                Resultado = CRUDTodos.PesquisarQuartosPreco(Integer.parseInt(txtPrecoMinQuartos.getText()), Integer.parseInt(txtPrecoMaxQuartos.getText()), c);
            }
            else{
                Resultado = CRUDTodos.PesquisarQuartos(c);
            }
            populaTabelaQuartos(Resultado);
            c.close();
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(TelaGerenciador.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnPesquisarQuartosActionPerformed

    private void btnAlterarQuartosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarQuartosActionPerformed
        // TODO add your handling code here:
        FormularioAlteracaoQuarto teste = new FormularioAlteracaoQuarto(QuartoIdselected);
        populaTabelaQuartos();
    }//GEN-LAST:event_btnAlterarQuartosActionPerformed

    private void btnApagarQuartosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApagarQuartosActionPerformed
        // TODO add your handling code here:
        if (QuartoIdselected >0)
            try{
                Connection c = myc.criaConexao();
                CRUDTodos.DeletarQuartos(QuartoIdselected, c);
                populaTabelaQuartos();
            } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(TelaGerenciador.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnApagarQuartosActionPerformed

    private void TabelaQuartosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaQuartosMousePressed
        // TODO add your handling code here:
        if (TabelaQuartos.getSelectedRow() != -1 && TabelaQuartos.getSelectedColumn() != -1 ){
        String id = TabelaQuartos.getModel().getValueAt(TabelaQuartos.getSelectedRow(),0) + "";
        try {
        Connection c = myc.criaConexao();
        populaSelecionadoQuartos(CRUDTodos.PesquisarQuartosId(Integer.parseInt(id),c));
        c.close();
        }
        catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(TelaGerenciador.class.getName()).log(Level.SEVERE, null, ex);
      }
    }
        
    }//GEN-LAST:event_TabelaQuartosMousePressed

    private void btnInserirQuartosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirQuartosActionPerformed
        // TODO add your handling code here:
         Quartos e =null;
        if(txtClienteIdQuartos.getText().length()>0){
        e= new Quartos(Integer.parseInt(txtHotelIdQuartos.getText()),Integer.parseInt(txtNumeroQuartos.getText()), Float.parseFloat(txtPrecoQuartos.getText()));
        if (e.isUsed())
        {
            try{
                Connection c = myc.criaConexao();
                CRUDTodos.InserirQuartos(e, c);
                populaTabelaQuartos();
            } 
            catch (SQLException | ClassNotFoundException ex) {
                Logger.getLogger(TelaGerenciador.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        }
        else{
        e = new Quartos(Integer.parseInt(txtHotelIdQuartos.getText()),Integer.parseInt(txtNumeroQuartos.getText()),Integer.parseInt(txtClienteIdQuartos.getText()), Float.parseFloat(txtPrecoQuartos.getText()));
        if (e.isUsed())
        {
            try{
                Connection c = myc.criaConexao();
                CRUDTodos.InserirQuartosHospedado(e, c);
                populaTabelaQuartos();
            } 
            catch (SQLException | ClassNotFoundException ex) {
                Logger.getLogger(TelaGerenciador.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        }
    }//GEN-LAST:event_btnInserirQuartosActionPerformed

    private void populaTabelaQuartos(){
        TabelaQuartos.removeAll();
        List<Quartos> quartos = new ArrayList<Quartos>();
        Quartos q = null;
        
        // Pega os dados do Banco de Dados
        try{
             Connection c = myc.criaConexao();
             ResultSet dados =  CRUDTodos.PesquisarQuartos(c);
             while (dados.next()){
                 q = new Quartos(
                                dados.getInt("HotelId"),
                                dados.getInt("numeroQuarto"),
                                dados.getInt("id_Cliente"),
                                dados.getFloat("preco"));
                 q.setQuartoID(dados.getInt("id_quarto"));
                 quartos.add(q);
             }
             
             c.close();
             
         } catch (ClassNotFoundException | SQLException er)       {
         }
    
       // Cria o modelo e associa com o List
       eModelQuartos = new quartoModeloDeTabela(quartos);
       
       // Associa o modelo à tabela
       TabelaQuartos.setModel(eModelQuartos);
    
    }
    
    private void populaSelecionadoQuartos(ResultSet dados) throws SQLException
    {
        dados.next();
        fotoQuarto = dados.getString("fotoQ");
        QuartoIdselected = dados.getInt("id_quarto");
        txtHotelIdQuartos.setText(dados.getInt("hotelid")+"");
        txtNumeroQuartos.setText(dados.getInt("numeroQuarto")+"");
        txtClienteIdQuartos.setText(dados.getInt("id_Cliente")+"");
        txtPrecoQuartos.setText(dados.getFloat("preco")+"");
    }
    
    private void populaTabelaQuartos(ResultSet dados){
        TabelaQuartos.removeAll();
        List<Quartos> quartos = new ArrayList<Quartos>();
        Quartos q = null;
        
        // Pega os dados do Banco de Dados
        try{
             Connection c = myc.criaConexao();
             while (dados.next()){
                 q = new Quartos(dados.getInt("HotelId"),
                                dados.getInt("numeroQuarto"),
                                dados.getInt("id_Cliente"),
                                dados.getFloat("preco"));
                 q.setQuartoID(dados.getInt("id_quarto"));
                 quartos.add(q);
             }
             
             c.close();
             
         } catch (ClassNotFoundException | SQLException er)       {
         }
    
       // Cria o modelo e associa com o List
       eModelQuartos = new quartoModeloDeTabela(quartos);
       
       // Associa o modelo à tabela
       TabelaQuartos.setModel(eModelQuartos);
    
    }
    
    
    /***
     * FIM DOS QUARTOS
     */
    
    
    /**
     * PARTE DAS CATEGORIAS
     */
    
    private void btnInserirCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirCatActionPerformed
        // TODO add your handling code here:
        Categoria e =null;
        e = new Categoria(txtCategoria.getText(), txtDescricao.getText());
        if (e.isUsed())
        {
            try{
                Connection c = myc.criaConexao();
                CRUDTodos.InserirCat(e, c);
                populaTabelaQuartos();
            } 
            catch (SQLException | ClassNotFoundException ex) {
                Logger.getLogger(TelaGerenciador.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnInserirCatActionPerformed

    private void btnAlterarCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarCatActionPerformed
        // TODO add your handling code here:
        FormularioAlteracaoCat teste = new FormularioAlteracaoCat(txtCategoria.getText());
        populaTabelaCat();
    }//GEN-LAST:event_btnAlterarCatActionPerformed

    private void btnExcluirCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirCatActionPerformed
        // TODO add your handling code here:
        if (txtCategoria.getText().length() >0)
            try{
                Connection c = myc.criaConexao();
                CRUDTodos.DeletarCat(txtCategoria.getText(), c);
                populaTabelaCat();
            } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(TelaGerenciador.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnExcluirCatActionPerformed

    private void btnPesquisarCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarCatActionPerformed
        // TODO add your handling code here:
        try{
            Connection C = myc.criaConexao();
            ResultSet resultado;
            if (txtCategoria.getText().length() > 0)
            {
                resultado = CRUDTodos.PesquisarCatNome(txtCategoria.getText(), C);
            }
            else if(txtDescricao.getText().length() > 0)
            {
                resultado = CRUDTodos.PesquisarCatDescricao(txtDescricao.getText(), C);
            }
            else
            {
                resultado = CRUDTodos.PesquisarCat(C);
            }
            populaTabelaCat(resultado);
            C.close();
        }
        catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(TelaGerenciador.class.getName()).log(Level.SEVERE, null, ex);
        }
            
    }//GEN-LAST:event_btnPesquisarCatActionPerformed

    private void TabelaCatMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaCatMousePressed
        // TODO add your handling code here:
        if (TabelaCat.getSelectedRow() != -1 && TabelaCat.getSelectedColumn() != -1 ){
        String categoria = TabelaCat.getModel().getValueAt(TabelaCat.getSelectedRow(),0) + "";
        try {
        Connection c = myc.criaConexao();
        populaSelecionadoCat(CRUDTodos.PesquisarCatNome(categoria,c));
        c.close();
        }
        catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(TelaGerenciador.class.getName()).log(Level.SEVERE, null, ex);
      }
    }
        
    }//GEN-LAST:event_TabelaCatMousePressed

    private void populaTabelaCat()
    {
        TabelaCat.removeAll();
        List<Categoria> cats = new ArrayList<Categoria>();
        Categoria cat = null;
        
        // Pega os dados do Banco de Dados
        try{
             Connection c = myc.criaConexao();
             ResultSet dados =  CRUDTodos.PesquisarCat(c);
             while (dados.next()){
                 cat = new Categoria(
                                dados.getString("CatNome"),
                                dados.getString("Descricao"));
                 cats.add(cat);
             }
             
             c.close();
             
         } catch (ClassNotFoundException | SQLException er)       {
         }
    
       // Cria o modelo e associa com o List
       eModelCategoria = new catModeloDeTabela(cats);
       
       // Associa o modelo à tabela
       TabelaCat.setModel(eModelCategoria);
    }
    private void populaSelecionadoCat(ResultSet dados) throws SQLException
    {
        dados.next();
        txtCategoria.setText(dados.getString("CatNome"));
        txtDescricao.setText(dados.getString("Descricao"));
    }
    private void populaTabelaCat(ResultSet dados) throws SQLException
    {
        TabelaCat.removeAll();
        List<Categoria> cats = new ArrayList<Categoria>();
        Categoria cat = null;
        
        // Pega os dados do Banco de Dados
        try{
             Connection c = myc.criaConexao();
             while (dados.next()){
                 cat = new Categoria(dados.getString("CatNome"),
                                dados.getString("Descricao"));
                 cats.add(cat);
             }
             
             c.close();
             
         } catch (ClassNotFoundException | SQLException er)       {
         }
    
       // Cria o modelo e associa com o List
       eModelCategoria = new catModeloDeTabela(cats);
       
       // Associa o modelo à tabela
       TabelaCat.setModel(eModelCategoria);
    
    }
    private void btnHotelEscolherFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHotelEscolherFotoActionPerformed
        // TODO add your handling code here:
        JPanel painel = new JPanel();
        JFileChooser escolher = new JFileChooser();
        painel.add(escolher);
        escolher.showOpenDialog(painel);
        if(escolher.getSelectedFile() != null){
            String path = escolher.getSelectedFile().getPath();
            fotoHotel = path;
        }
        
    }//GEN-LAST:event_btnHotelEscolherFotoActionPerformed

    private void btnVisualizarFotoHotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisualizarFotoHotelActionPerformed
        // TODO add your handling code here:
        
        if (fotoHotel.length()>0){
            JPanel background= new JPanel(){
            @Override
            protected void paintComponent(Graphics g) {
                    try {
                        Image t = criarImagem(fotoHotel);
                        Graphics2D graphics2d = (Graphics2D) g;
                        graphics2d.drawImage(t, 0, 0,450,450, null);
                        super.paintComponents(g);
                    } catch (IOException ex) {
                        Logger.getLogger(TelaGerenciador.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            };
            JFrame foto = new JFrame("IMAGEM DO HOTEL " + new File(fotoHotel).getName().substring(0, 2));
            foto.add(background);
            foto.setVisible(true);
            foto.setSize(450,450);
            foto.setLayout(new GridLayout(1,1));
            foto.setDefaultCloseOperation(HIDE_ON_CLOSE);
            
        }
        
    }//GEN-LAST:event_btnVisualizarFotoHotelActionPerformed

    private void btnQuartoEscolherFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuartoEscolherFotoActionPerformed
        // TODO add your handling code here:
        JPanel painel = new JPanel();
        JFileChooser escolher = new JFileChooser();
        painel.add(escolher);
        escolher.showOpenDialog(painel);
        if(escolher.getSelectedFile() != null){
            String path = escolher.getSelectedFile().getPath();
            fotoQuarto = path;
        }
    }//GEN-LAST:event_btnQuartoEscolherFotoActionPerformed

    private void btnVisualizarFotoQuartoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisualizarFotoQuartoActionPerformed
        // TODO add your handling code here:
        if (fotoQuarto.length()>0){
            JPanel background= new JPanel(){
            @Override
            protected void paintComponent(Graphics g) {
                    try {
                        Image t = criarImagem(fotoQuarto);
                        Graphics2D graphics2d = (Graphics2D) g;
                        graphics2d.drawImage(t, 0, 0,450,450, null);
                        super.paintComponents(g);
                    } catch (IOException ex) {
                        Logger.getLogger(TelaGerenciador.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            };
            JFrame foto = new JFrame("IMAGEM DO QUARTO " + new File(fotoQuarto).getName().substring(0, 2));
            foto.add(background);
            foto.setVisible(true);
            foto.setSize(450,450);
            foto.setLayout(new GridLayout(1,1));
            foto.setDefaultCloseOperation(HIDE_ON_CLOSE);
            
        }
    }//GEN-LAST:event_btnVisualizarFotoQuartoActionPerformed

    public Image criarImagem(String path) throws IOException
    {
        Image imgHotel = ImageIO.read(new File(path));
        return imgHotel;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaGerenciador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaGerenciador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaGerenciador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaGerenciador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaGerenciador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TabelaCat;
    private javax.swing.JTable TabelaHoteis;
    private javax.swing.JTable TabelaQuartos;
    private javax.swing.JButton btnAlterarCat;
    private javax.swing.JButton btnAlterarHotel;
    private javax.swing.JButton btnAlterarQuartos;
    private javax.swing.JButton btnApagarHotel;
    private javax.swing.JButton btnApagarQuartos;
    private javax.swing.JButton btnExcluirCat;
    private javax.swing.JButton btnHotelEscolherFoto;
    private javax.swing.JButton btnInserirCat;
    private javax.swing.JButton btnInserirHotel;
    private javax.swing.JButton btnInserirQuartos;
    private javax.swing.JButton btnPesquisarCat;
    private javax.swing.JButton btnPesquisarQuartos;
    private javax.swing.JButton btnQuartoEscolherFoto;
    private javax.swing.JButton btnVisualizarFotoHotel;
    private javax.swing.JButton btnVisualizarFotoQuarto;
    private javax.swing.JButton jButton14;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField txtBuscaCategoriaQuarto;
    private javax.swing.JTextField txtCategoria;
    private javax.swing.JTextField txtCategoriaBuscaHotel;
    private javax.swing.JTextField txtCategoriaBuscar;
    private javax.swing.JTextField txtCategoriaH;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtCidadeBuscaHotel;
    private javax.swing.JTextField txtClienteIdQuartos;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtDescricaoBuscar;
    private javax.swing.JTextField txtHotelIdQuartos;
    private javax.swing.JTextField txtHotelNome;
    private javax.swing.JTextField txtNomeBuscaH;
    private javax.swing.JTextField txtNumeroQuartos;
    private javax.swing.JTextField txtPrecoMaxQuartos;
    private javax.swing.JTextField txtPrecoMinQuartos;
    private javax.swing.JTextField txtPrecoQuartos;
    private javax.swing.JTextField txtQuartosHotelBusca;
    private javax.swing.JTextField txtRating;
    private javax.swing.JTextField txtRatingBusca1;
    private javax.swing.JTextField txtRatingBusca2;
    private javax.swing.JTextField txtRua;
    // End of variables declaration//GEN-END:variables
}
